### PR TITLE
Image provider implementation for fast cached image package

### PR DESCRIPTION
**Pull request by MerdanDev**
@CHRISTOPANANJICKAL are you online can you just check this pr?

### CODE REVIEW

**Comment by MerdanDev** [comment]
adding image provider implementation for fast cache image is merging

**Comment by CHRISTOPANANJICKAL** [comment]
Sure. I'll merge it in the weekend. Thanks for the PR

**Comment by CHRISTOPANANJICKAL** [comment]
> @CHRISTOPANANJICKAL are you online can you just check this pr?

Hii @MerdanDev , Can we have a discussion on this PR?

**Comment by MerdanDev** [comment]
@CHRISTOPANANJICKAL yes we can.

**Comment by CHRISTOPANANJICKAL** [comment]
> @CHRISTOPANANJICKAL yes we can.

When will you be available? If you are free can we have it now?

**Comment by MerdanDev** [comment]
> When will you be available? Can you schedule a call?

Oh by phone number I can't call, maybe by skype if you want. Another way is we can discus it by chat. 
I personally prefer linkdeIn bcs most of messangers are censored here. My [LinkedIn](https://linkedin.com/in/merdan-atamyradow).

**Comment by CHRISTOPANANJICKAL** [comment]
> 

Sure

**Comment by MerdanDev** [comment]
In this [commit](https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/pull/8/commits/5273ca98befcc730438ba792d116f5e8f10ec853) I have used dio for getting image bytes from network. Can you check it?

**Comment by WiRight** [comment]
Any update?

**Pull request merged**
