### PR TITLE
Support for web

### PR DESCRIPTION
**Pull request by woutervanwijk**
Small changes so the package also works on the web

### CODE REVIEW

**Comment by CHRISTOPANANJICKAL** [comment]
Thankyou @woutervanwijk for you effort and contribution. ill merge the code soon

**Comment by CHRISTOPANANJICKAL** [comment]
Hii @woutervanwijk  i have cloned the pull request and gave it a test run in an android device. I got this error.  Please have a look.

**Comment by woutervanwijk** [comment]
> Hii @woutervanwijk I have cloned the pull request and gave it a test run on an Android device with the example/main.dart. I got this error. Please have a look.
> 
> "Unhandled Exception: HiveError: You need to initialize Hive or provide a path to store the box."
> 
> image

Forgot an await! 

Since it uses hive_flutter now, I also removed the path requirement

**Comment by CHRISTOPANANJICKAL** [comment]
@woutervanwijk  the package has been updated with some more features. Now the PR is having some conflicts. Can you please fix them so that I can merge the PR

**Comment by woutervanwijk** [comment]
Fixed the conflicts!

**Comment by woutervanwijk** [comment]
Did you have time to look at this? The conflict is gone

**Comment by CHRISTOPANANJICKAL** [comment]
> Did you have time to look at this? The conflict is gone

Ill check and merge this weekend bro. I was having a busy schedule for the past few weeks. Once again thanks for the update.

**Comment by CHRISTOPANANJICKAL** [comment]
PR accepted. Sorry for the long delay. Thanks for your contribution @woutervanwijk .

**Pull request merged**
