### PR TITLE
Fix #9

### LINKED ISSUE #9: HiveError: String keys need to be a max length of 255 - Image url
When I'm trying to load an image from AWS (very long link), the package gives me an error:
`HiveError: String keys need to be a max length of 255 - Image url : (here is link)`

### PR DESCRIPTION
**Pull request by stevenosse**
This PR fixes #9 

- Use uuid instead of url as image key
- Migrate old cache keys to new keys

Thank you.

### CODE REVIEW

**Comment by CHRISTOPANANJICKAL** [comment]
Thanks for the PR. I guess line length must be 80 in dart to get 20 pub points when publishing to pub.dev. Can you please update that?


Please go through this 
[Link](https://dart.dev/guides/libraries/writing-package-pages#:~:text=Keep%20the%20line%20length%20%3C%3D%2080,format%20or%20flutter%20format%20would).)

**Comment by stevenosse** [comment]
> Thanks for the PR. I guess line length must be 80 in dart to get 20 pub points when publishing to pub.dev. Can you please update that?
> 
> Please go through this[Link](https://dart.dev/guides/libraries/writing-package-pages#:~:text=Keep%20the%20line%20length%20%3C%3D%2080,format%20or%20flutter%20format%20would)

Yeah sure, was'nt aware of that, will fix this :)

**Comment by stevenosse** [comment]
Done :)

**Comment by GeylanKalafMohe** [comment]
This issue still happens please fix it

**Pull request merged**
